export const services = [
	{
		id: 1,
		bg: '/intro/med.png',
		text: 'Медицинские услуги',
		href: '/services',
		rightSide: true,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Медицинские услуги',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Медицинские услуги',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Медицинские услуги',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Медицинские услуги',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Медицинские услуги',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Медицинские услуги',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 2,
		bg: '/intro/anal.png',
		text: 'Анализы',
		href: '/services',
		rightSide: true,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Анализы',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Анализы',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Анализы',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Анализы',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Анализы',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Анализы',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 3,
		bg: '/intro/stoma.png',
		text: 'Стоматология',
		href: '/services',
		rightSide: true,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Стоматология',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Стоматология',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Стоматология',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Стоматология',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Стоматология',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Стоматология',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 4,
		bg: '/intro/pills.png',
		text: 'Аптека',
		href: '/services',
		rightSide: false,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Аптека',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Аптека',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Аптека',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Аптека',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Аптека',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Аптека',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 5,
		bg: '/intro/rengen.png',
		text: 'Ренгенология',
		href: '/services',
		rightSide: false,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Ренгенология',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Ренгенология',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Ренгенология',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Ренгенология',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Ренгенология',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Ренгенология',
				href: '/services',
				rightSide: false,
			},
		],
	},
	{
		id: 6,
		bg: '/intro/netradi.png',
		text: 'Нетрадиционная Медицина',
		href: '/services',
		rightSide: false,
		subItems: [
			{
				id: 1,
				bg: '/intro/buble.svg',
				text: 'Нетрадиционная Медицина',
				href: '/services',
				rightSide: true,
			},
			{
				id: 2,
				bg: '/intro/buble.svg',
				text: 'Нетрадиционная Медицина',
				href: '/services',
				rightSide: true,
			},
			{
				id: 3,
				bg: '/intro/buble.svg',
				text: 'Нетрадиционная Медицина',
				href: '/services',
				rightSide: true,
			},
			{
				id: 4,
				bg: '/intro/buble.svg',
				text: 'Нетрадиционная Медицина',
				href: '/services',
				rightSide: false,
			},
			{
				id: 5,
				bg: '/intro/buble.svg',
				text: 'Нетрадиционная Медицина',
				href: '/services',
				rightSide: false,
			},
			{
				id: 6,
				bg: '/intro/buble.svg',
				text: 'Нетрадиционная Медицина',
				href: '/services',
				rightSide: false,
			},
		],
	},
];
