export const services = [
	{
		id: 1,
		bg: '@/public/intro/tea.png',
		text: 'Медицинские услуги',
		href: '#',
		rightSide: true,
		subItems: [
			{
				id: 1,
				bg: '@/public/intro/tea.png',
				text: 'Медицинские услуги',
				href: '#',
				rightSide: true,
			},
			{
				id: 2,
				bg: '@/public/intro/tea.png',
				text: 'Медицинские услуги',
				href: '#',
				rightSide: true,
			},
			{
				id: 3,
				bg: '@/public/intro/tea.png',
				text: 'Медицинские услуги',
				href: '#',
				rightSide: true,
			},
			{
				id: 4,
				bg: '@/public/intro/tea.png',
				text: 'Медицинские услуги',
				href: '#',
				rightSide: false,
			},
			{
				id: 5,
				bg: '@/public/intro/tea.png',
				text: 'Медицинские услуги',
				href: '#',
				rightSide: false,
			},
			{
				id: 6,
				bg: '@/public/intro/tea.png',
				text: 'Медицинские услуги',
				href: '#',
				rightSide: false,
			},
		],
	},
	{
		id: 2,
		bg: '@/public/intro/tea.png',
		text: 'Анализы',
		href: '#',
		rightSide: true,
		subItems: [
			{
				id: 1,
				bg: '@/public/intro/tea.png',
				text: 'Анализы',
				href: '#',
				rightSide: true,
			},
			{
				id: 2,
				bg: '@/public/intro/tea.png',
				text: 'Анализы',
				href: '#',
				rightSide: true,
			},
			{
				id: 3,
				bg: '@/public/intro/tea.png',
				text: 'Анализы',
				href: '#',
				rightSide: true,
			},
			{
				id: 4,
				bg: '@/public/intro/tea.png',
				text: 'Анализы',
				href: '#',
				rightSide: false,
			},
			{
				id: 5,
				bg: '@/public/intro/tea.png',
				text: 'Анализы',
				href: '#',
				rightSide: false,
			},
			{
				id: 6,
				bg: '@/public/intro/tea.png',
				text: 'Анализы',
				href: '#',
				rightSide: false,
			},
		],
	},
	{
		id: 3,
		bg: '@/public/intro/tea.png',
		text: 'Стоматология',
		href: '#',
		rightSide: true,
		subItems: [
			{
				id: 1,
				bg: '@/public/intro/tea.png',
				text: 'Стоматология',
				href: '#',
				rightSide: true,
			},
			{
				id: 2,
				bg: '@/public/intro/tea.png',
				text: 'Стоматология',
				href: '#',
				rightSide: true,
			},
			{
				id: 3,
				bg: '@/public/intro/tea.png',
				text: 'Стоматология',
				href: '#',
				rightSide: true,
			},
			{
				id: 4,
				bg: '@/public/intro/tea.png',
				text: 'Стоматология',
				href: '#',
				rightSide: false,
			},
			{
				id: 5,
				bg: '@/public/intro/tea.png',
				text: 'Стоматология',
				href: '#',
				rightSide: false,
			},
			{
				id: 6,
				bg: '@/public/intro/tea.png',
				text: 'Стоматология',
				href: '#',
				rightSide: false,
			},
		],
	},
	{
		id: 4,
		bg: '@/public/intro/tea.png',
		text: 'Аптека',
		href: '#',
		rightSide: false,
		subItems: [
			{
				id: 1,
				bg: '@/public/intro/tea.png',
				text: 'Аптека',
				href: '#',
				rightSide: true,
			},
			{
				id: 2,
				bg: '@/public/intro/tea.png',
				text: 'Аптека',
				href: '#',
				rightSide: true,
			},
			{
				id: 3,
				bg: '@/public/intro/tea.png',
				text: 'Аптека',
				href: '#',
				rightSide: true,
			},
			{
				id: 4,
				bg: '@/public/intro/tea.png',
				text: 'Аптека',
				href: '#',
				rightSide: false,
			},
			{
				id: 5,
				bg: '@/public/intro/tea.png',
				text: 'Аптека',
				href: '#',
				rightSide: false,
			},
			{
				id: 6,
				bg: '@/public/intro/tea.png',
				text: 'Аптека',
				href: '#',
				rightSide: false,
			},
		],
	},
	{
		id: 5,
		bg: '@/public/intro/tea.png',
		text: 'Ренгенология',
		href: '#',
		rightSide: false,
		subItems: [
			{
				id: 1,
				bg: '@/public/intro/tea.png',
				text: 'Ренгенология',
				href: '#',
				rightSide: true,
			},
			{
				id: 2,
				bg: '@/public/intro/tea.png',
				text: 'Ренгенология',
				href: '#',
				rightSide: true,
			},
			{
				id: 3,
				bg: '@/public/intro/tea.png',
				text: 'Ренгенология',
				href: '#',
				rightSide: true,
			},
			{
				id: 4,
				bg: '@/public/intro/tea.png',
				text: 'Ренгенология',
				href: '#',
				rightSide: false,
			},
			{
				id: 5,
				bg: '@/public/intro/tea.png',
				text: 'Ренгенология',
				href: '#',
				rightSide: false,
			},
			{
				id: 6,
				bg: '@/public/intro/tea.png',
				text: 'Ренгенология',
				href: '#',
				rightSide: false,
			},
		],
	},
	{
		id: 6,
		bg: '@/public/intro/tea.png',
		text: 'Нетрадиционная Медицина',
		href: '#',
		rightSide: false,
		subItems: [
			{
				id: 1,
				bg: '@/public/intro/tea.png',
				text: 'Нетрадиционная Медицина',
				href: '#',
				rightSide: true,
			},
			{
				id: 2,
				bg: '@/public/intro/tea.png',
				text: 'Нетрадиционная Медицина',
				href: '#',
				rightSide: true,
			},
			{
				id: 3,
				bg: '@/public/intro/tea.png',
				text: 'Нетрадиционная Медицина',
				href: '#',
				rightSide: true,
			},
			{
				id: 4,
				bg: '@/public/intro/tea.png',
				text: 'Нетрадиционная Медицина',
				href: '#',
				rightSide: false,
			},
			{
				id: 5,
				bg: '@/public/intro/tea.png',
				text: 'Нетрадиционная Медицина',
				href: '#',
				rightSide: false,
			},
			{
				id: 6,
				bg: '@/public/intro/tea.png',
				text: 'Нетрадиционная Медицина',
				href: '#',
				rightSide: false,
			},
		],
	},
];
